name:  Release to PyPI

on:
  push:
    tags:
       - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies for testing
        run: |
          sudo apt update
          sudo apt install libsndfile1

          pip install pytest
          pip install zarr
          pip install setuptools wheel twine
          pip install .
      - name: Test core with pytest
        run: |
          pytest -v
      - name: Publish on PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.AIND_PYPI_TOKEN }}
        run: |
          python setup.py sdist
          twine upload dist/*
